name = "MPASMeshes"
uuid = "55014cf3-5e3e-4aa4-8df2-e07191383b05"
authors = ["Felipe A. V. de Bragan√ßa Alves <favbalves@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SmallCollections = "2b935e18-93d6-40ac-ae34-fe54c09f00e1"
TensorsLite = "1a1b94bd-d244-45e0-965a-8acfeb92b70f"
TensorsLiteGeometry = "f9cc0174-84f8-4243-a119-6cf6c33db921"
VoronoiMeshes = "978c199f-fe38-4011-9fe6-317bc1cdd350"
VoronoiOperators = "28deb5e7-6037-4488-9d39-5419413b6983"
Zeros = "bd1ec220-6eb4-527a-9b49-e79c3db6233b"

[weakdeps]
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[extensions]
NCDatasetsExt = ["VoronoiMeshes", "NCDatasets"]

[compat]
NCDatasets = "0.14.6"
PrecompileTools = "1.2.1"
Random = "1.11.0"
Reexport = "1.2.2"
SmallCollections = "0.4.1, 0.5"
Zeros = "0.4"
julia = "1.10"

[extras]
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "NCDatasets"]
